efficiency_vars = [
  "pt",
  "eta",
  "phi",
  "pdgIdBin",
  "nImmediateDau",
  "nFinalDau",
  "ntrk",
  "x",
  "y",
  "z",
  "dxy",
  "dz",
  "d3d",
  "dxysig",
  "dzsig",
  "d3dsig"
]
eff_var_labels = [
  "Mother p_{T} [GeV]",
  "Mother #eta",
  "Mother #phi",
  "Mother hadron",
  "# of immediate daughters",
  "# of stable daughters",
  "# of daughters",
  "x [cm]",
  "y [cm]",
  "z [cm]",
  "d_{xy} [cm]",
  "d_{z} [cm]",
  "d_{3D} [cm]",
  "d_{xy} significance",
  "d_{z} significance",
  "d_{3D} significance"
]
