gv_names = ["gv", "gvB", "gvD"]

gv_vars = [
  "trk_pt",
  "trk_pt2",
  "trk_eta",
  "trk_phi",
  "trk_charge",
  "x",
  "y",
  "z",
  "pt",
  "pt2",
  "eta",
  "phi",
  "pdgIdBin",
  "nImmediateDau",
  "nFinalDau",
  "ntrk",
  "dxy",
  "dz",
  "d3d",
  "dxyerr",
  "dzerr",
  "d3derr",
  "dxysig",
  "dzsig",
  "d3dsig"
]
gv_var_labels = [
  "Daughter p_{T} [GeV]",
  "Daughter p_{T}^{2} [GeV^{2}]",
  "Daughter #eta",
  "Daughter #phi",
  "Daughter charge",
  "x [cm]",
  "y [cm]",
  "z [cm]",
  "Mother p_{T} [GeV]",
  "Mother p_{T}^{2} [GeV^{2}]",
  "Mother #eta",
  "Mother #phi",
  "Mother hadron",
  "# of immediate daughters",
  "# of stable daughters",
  "# of charged, stable daughters",
  "d_{xy} [cm]",
  "d_{z} [cm]",
  "d_{3D} [cm]",
  "d_{xy} error [cm]",
  "d_{z} error [cm]",
  "d_{3D} error [cm]",
  "d_{xy} significance",
  "d_{z} significance",
  "d_{3D} significance"
]
